server:
  port: 8082
spring:
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  jpa:
    show-sql: true

